nodeLinker: node-modules

packageExtensions:
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/typescript-build@*":
    peerDependencies:
      webpack: "*"
  jest@*:
    peerDependencies:
      "@babel/core": "*"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
